import { Product } from '../core/models/product.model';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'Coffee Bocat',
    name: 'Coffee Bocat',
    imageUrl: 'https://picsum.photos/seed/coffee1/60/60',
    buyingPrice: 3.0,
    sellingPrice: 3.0,
    currentStock: 20,
    stockReorderStatus: 'not-reorder',
    category: 'Beverages',
  },
  {
    id: '2',
    sku: 'Switch Sandwich',
    name: 'Switch Sandwich',
    imageUrl: 'https://picsum.photos/seed/sandwich1/60/60',
    buyingPrice: 1.0,
    sellingPrice: 2.0,
    currentStock: 12,
    stockReorderStatus: 'pastry',
    category: 'Food',
  },
  {
    id: '3',
    sku: 'Flowny Pastry',
    name: 'Flowny Pastry',
    imageUrl: 'https://picsum.photos/seed/pastry1/60/60',
    buyingPrice: 3.0,
    sellingPrice: 3.0,
    currentStock: 2,
    stockReorderStatus: 'good',
    category: 'Pastries',
  },
  {
    id: '4',
    sku: 'Pastry',
    name: 'Pastry',
    imageUrl: 'https://picsum.photos/seed/pastry2/60/60',
    buyingPrice: 3.0,
    sellingPrice: 3.0,
    currentStock: 30,
    stockReorderStatus: 'not-reorder',
    category: 'Pastries',
  },
  {
    id: '5',
    sku: 'Beat Buffein',
    name: 'Beat Buffein',
    imageUrl: 'https://picsum.photos/seed/beat1/60/60',
    buyingPrice: 1.0,
    sellingPrice: 3.0,
    currentStock: 21,
    stockReorderStatus: 'pastry',
    category: 'Beverages',
  },
  {
    id: '6',
    sku: 'Pastry Iclt',
    name: 'Pastry Iclt',
    imageUrl: 'https://picsum.photos/seed/pastry3/60/60',
    buyingPrice: 3.0,
    sellingPrice: 4.0,
    currentStock: 20,
    stockReorderStatus: 'not-reorder',
    category: 'Pastries',
  },
  {
    id: '7',
    sku: 'Sandwicies',
    name: 'Sandwicies',
    imageUrl: 'https://picsum.photos/seed/sandwich2/60/60',
    buyingPrice: 4.0,
    sellingPrice: 4.0,
    currentStock: 36,
    stockReorderStatus: 'pasout',
    category: 'Food',
  },
  {
    id: '8',
    sku: 'Latte Special',
    name: 'Latte Special',
    imageUrl: 'https://picsum.photos/seed/latte1/60/60',
    buyingPrice: 2.5,
    sellingPrice: 4.5,
    currentStock: 15,
    stockReorderStatus: 'good',
    category: 'Beverages',
  },
];
